name: fx_assistant
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.5
  - pip
  - pip:
    - openai==1.55.3
    - matplotlib==3.9.0
    - requests==2.32.3
    - beautifulsoup4==4.12.3
    - asyncio==3.4.3
    - aiohttp==3.9.5
    - yfinance==0.2.40
    - python-dotenv==1.0.1
    - ta==0.11.0
    - langchain==0.2.6
    - langchain-openai==0.1.14
    - streamlit==1.36.0
    - selenium==4.23.1
    - webdriver-manager==4.0.2
    - pdfplumber==0.11.4
    - httpx
    - mplfinance==0.12.10b0
    - google-genai==1.4.0
    - technical-analysis==0.0.6
    - pandas==2.2.3
    - numpy
    - twelvedata[pandas,matplotlib]==1.2.24
    - aiofiles==24.1.0
    - websocket-client==1.8.0
    - tabulate==0.9.0
    - fastapi==0.115.12
    - uvicorn==0.34.2














