name: fx_assistant
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.5
  - pandas=2.2.2
  - numpy=2.0.0
  - pip
  - pip:
    - openai==1.35.7
    - matplotlib==3.9.0
    - requests==2.32.3
    - beautifulsoup4==4.12.3
    - asyncio==3.4.3
    - aiohttp==3.9.5
    - yfinance==0.2.40
    - python-dotenv==1.0.1
    - ta==0.11.0
    - langchain==0.2.6
    - langchain-openai==0.1.14
    - selenium==4.22.0
    - webdriver-manager==4.0.1






